# Generated by Django 5.0.6 on 2024-05-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
